export const DASHBOARD_ACTION_TYPES = {
  FETCH_DASHBOARD_START: "dashboard/FETCH_DASHBOARD_START",
  FETCH_DASHBOARD_SUCCESS: "dashboard/FETCH_DASHBOARD_SUCCESS",
  FETCH_DASHBOARD_FAILED: "dashboard/FETCH_DASHBOARD_FAILED",
  UPDATE_IS_HOME_PAGE: "dashboard/UPDATE_IS_HOME_PAGE",
};
